# Generated by Django 4.1.3 on 2022-11-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=45)),
                ('paragrafo', models.TextField(max_length=255)),
                ('titulo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('videos', models.FileField(blank=True, upload_to='')),
                ('imagens', models.ImageField(blank=True, upload_to='')),
                ('audios', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoresp', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativas', models.CharField(max_length=100)),
                ('texto_per', models.TextField(blank=True, max_length=100, null=True)),
                ('conteudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='core.conteudo')),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='core.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data_inicial', models.DateField(blank=True, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios', to='core.pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='id_midia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteudo', to='core.midia'),
        ),
    ]
