# Generated by Django 4.1.4 on 2022-12-10 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conteudo",
            name="criado_por",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conteudos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conteudo",
            name="paragrafo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conteudo",
            name="disciplina",
            field=models.CharField(
                choices=[
                    ("Português", "Portugues"),
                    ("Matemática", "Matematica"),
                    ("Geografia", "Geografia"),
                    ("História", "Historia"),
                ],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Disciplina",
        ),
    ]
