# Generated by Django 4.1.1 on 2022-09-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='site',
        ),
    ]
