# Generated by Django 4.1.4 on 2022-12-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_conteudo_criado_por_conteudo_paragrafo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternativa",
            name="texto_alternativas",
        ),
        migrations.AddField(
            model_name="alternativa",
            name="texto_alternativa",
            field=models.CharField(default="", max_length=255),
        ),
    ]
