# Generated by Django 4.1.3 on 2022-12-08 04:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_midia_audios_alter_midia_imagens_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_alternativas", models.CharField(max_length=150)),
                ("esta_correta", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name="conteudo",
            name="id_midia",
        ),
        migrations.RemoveField(
            model_name="conteudo",
            name="paragrafo",
        ),
        migrations.RemoveField(
            model_name="conteudo",
            name="titulo",
        ),
        migrations.RemoveField(
            model_name="conteudo",
            name="topico",
        ),
        migrations.RemoveField(
            model_name="formulario",
            name="data_inicial",
        ),
        migrations.RemoveField(
            model_name="formulario",
            name="pergunta",
        ),
        migrations.RemoveField(
            model_name="pergunta",
            name="conteudo",
        ),
        migrations.RemoveField(
            model_name="pergunta",
            name="resposta",
        ),
        migrations.RemoveField(
            model_name="pergunta",
            name="texto_per",
        ),
        migrations.AddField(
            model_name="conteudo",
            name="nome",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="formulario",
            name="conteudo",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.conteudo",
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="criado_por",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="formularios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 12, 8, 4, 0, 54, 902347, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario",
            name="perguntas",
            field=models.ManyToManyField(related_name="+", to="core.pergunta"),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="texto_pergunta",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="titulo",
            field=models.CharField(
                default="New Form", max_length=255, verbose_name="Form Title"
            ),
        ),
        migrations.RemoveField(
            model_name="pergunta",
            name="alternativas",
        ),
        migrations.DeleteModel(
            name="Midia",
        ),
        migrations.DeleteModel(
            name="Resposta",
        ),
        migrations.AddField(
            model_name="conteudo",
            name="disciplina",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conteudos",
                to="core.disciplina",
            ),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="alternativas",
            field=models.ManyToManyField(related_name="+", to="core.alternativa"),
        ),
    ]
