# Generated by Django 4.1.3 on 2022-12-08 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alternativa_disciplina_remove_conteudo_id_midia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conteudo",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conteudos",
                to="core.disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="conteudo",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="conteudo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.conteudo"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="formularios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pergunta",
            name="texto_pergunta",
            field=models.CharField(max_length=150),
        ),
    ]
